#!/bin/bash
set -e

# 指定したディレクトリの管理対象の全ファイル・ディレクトリ名に、連番を追加（変更）する。
# 第1引数として、処理対象のディレクトリを指定する。（デフォルトはカレントディレクトリ）

# 実行例
# fn-add-all
# fn-add-all sample/01_hoge

# 引数の解析
# 末尾のスラッシュは除去する。
directory="${1:-.}"
directory="${directory%/}"

# 各値の算出
digit=$(fn-digit "$directory")
max_number=$((10 ** digit - 1))

# 指定ディレクトリに対しての処理
i=1
find "$directory" -depth 1 | fn-file-added | sort | while read -r file_path; do
  # 連番が最大値以外の場合は変更する。
  number=$(fn-number "$file_path")
  if [ "$number" -ne "$max_number" ] ; then
    fn-add $i "$file_path"
    ((i++))
  fi
done

# サブディレクトリに対しての処理
find "$directory" -depth 1 -type d | fn-file-added | while read -r sub_directory; do
  fn-add-all "$sub_directory"
done
