#!/bin/bash
set -e

# 指定したファイル・ディレクトリの連番を変更する。
# 第1引数として、ファイル・ディレクトリを指定する。
# 第2引数として、連番を指定する。（デフォルトは連番なし）

# 実行例
# fn-apply sample/01_hoge
# fn-apply sample/01_hoge 12
# fn-apply sample/01_hoge/01_hoge01
# fn-apply sample/01_hoge/01_hoge01 12

# 引数の解析
old_path="$1"
new_number="$2"

# ファイル・ディレクトリ名の変更
new_path=$(fn-get-path "$old_path" "$new_number")
if [ "$old_path" != "$new_path" ]; then
  mv "$old_path" "$new_path"
  echo "Name changed! $old_path -> $new_path"
fi
