#!/bin/bash
set -e

# ファイル・ディレクトリ名に、連番を追加（変更）する。
# 第1引数として、連番を指定する。
# 第2引数として、ファイル・ディレクトリ名を指定する。

# 実行例
# fn-add 12 sample/01_hoge
# fn-add 12 sample/01_hoge/01_aaa
# fn-add 12 sample/01_hoge/eee

# 引数の解析
new_number="$1"
old_path="$2"

# 各値の算出
directory=$(dirname "$old_path")
digit=$(fn-config-digit "$directory")
new_number_string=$(printf "%0${digit}d" "$new_number")
file_name=$(fn-get-name "$old_path")
new_path=${directory}/${new_number_string}_${file_name}

# ファイル・ディレクトリ名の変更
if [ "$old_path" != "$new_path" ]; then
  mv "$old_path" "$new_path"
  echo "Name changed! $old_path -> $new_path"
fi
