#!/bin/bash
set -e

# 設定ファイルから、各種設定値を取得する。
# 設定ファイルが存在しない場合は、"../.fn.json"が使用される。
# 第1引数として、ディレクトリを指定する。（デフォルトはカレントディレクトリ）
# "-q"オプションで、適用するjq表現を指定できる。

# 実行例
# fn-config
# fn-config sample
# fn-config -q .digit
# fn-config -q .digit sample

# オプションの解析
while getopts q: opt; do
  case $opt in
    q) jq_expression="$OPTARG";;
    *) exit 1;;
  esac
done
shift $((OPTIND - 1))

# 引数の解析
# 末尾のスラッシュは除去する。
directory="${1:-.}"
directory="${directory%/}"

# 設定ファイルの読み取り
config_file="${directory}/.fn.json"
[ -f "$config_file" ] || config_file="$(dirname "$0")/../.fn.json"
# TODO ファイル内に設定値がない、または不正な場合の考慮
jq -r "$jq_expression" "$config_file"
