#!/bin/bash
set -e

# 設定ファイルから、各種設定値を取得する。
# 設定ファイルが存在しない場合は、"../.file-numbering.json"が使用される。
# 第1引数として、ディレクトリを指定する。（デフォルトはカレントディレクトリ）
# "-q"オプションで、適用するjq表現を指定できる。
# TODO 設定ファイルをYAMLでも書けるようにする。

# 実行例
# fn-config
# fn-config sample
# fn-config -q .digit
# fn-config -q .digit sample

# オプションの解析
jq_expression="."
while getopts q: opt; do
  case $opt in
    q) jq_expression="$OPTARG";;
    *) exit 1;;
  esac
done
shift $((OPTIND - 1))

# 引数の解析
# 末尾のスラッシュは除去する。
directory="${1:-.}"
directory="${directory%/}"

# 設定ファイルをマージして読み取る。（カレントディレクトリのファイル、デフォルトのファイルの順で優先して読み取る）
config_file_current="${directory}/.file-numbering.json"
config_file_default="$(dirname "$0")/../.file-numbering.json"
if [ -f "$config_file_current" ]; then
  jq -sr "add | $jq_expression" "$config_file_default" "$config_file_current"
else
  jq -r "$jq_expression" "$config_file_default"
fi
