#!/bin/bash

# File Number Clean
# ファイル名の連番を振り直す。
# 引数として、処理対象のディレクトリを指定する。（デフォルトはカレントディレクトリ）
# `-d 桁数`オプションで、連番桁数を指定できる。（デフォルトは`2`）
# TODO サブディレクトリを遡り、連番をそれぞれ振る

# オプションの解析
digit=2
while getopts f:d: opt; do
  case $opt in
    d) digit="$OPTARG";;
    *) exit 1;;
  esac
done
shift $((OPTIND - 1))

i=1
find "${1:-.}" -depth 1 | fn-filter | sort | while read -r file_path; do
  fn-mod -d "$digit" $i "$file_path"
  ((i++))
done
