#!/bin/bash
set -e

# File Number Clean
# ファイル名の連番を振り直す。
# 第1引数として、処理対象のディレクトリを指定する。（デフォルトはカレントディレクトリ）

# 引数の解析
# 末尾のスラッシュは除去する。
directory="${1:-.}"
directory="${directory%/}"

# 各値の算出
digit=$(fn-digit "$directory")
max_number=$((10 ** digit - 1))

# 指定ディレクトリに対しての処理
i=1
find "$directory" -depth 1 | fn-filter | sort | while read -r file_path; do
  # 連番が最大値以外の場合は変更する。
  number=$(fn-number "$file_path")
  if [ "$number" -ne "$max_number" ] ; then
    fn-add $i "$file_path"
    ((i++))
  fi
done

# サブディレクトリに対しての処理
find "$directory" -depth 1 -type d | fn-filter | while read -r sub_directory; do
  fn-clean "$sub_directory"
done
