#!/bin/bash
set -e

# ファイル名から連番を取得する。
# 標準入力として、ファイル名を指定する。

# 実行例
# find sample/01_hoge -depth 1 | fn-file-number

while read -r file_path; do
  basename "$file_path" | grep -oE "^[0-9]+" | perl -pe "s/^0*([0-9]+)$/\1/"
done
