#!/bin/bash
set -e

# 連番が最大値以外のファイル名のみを出力する。
# 標準入力として、ファイル名を指定する。

# 実行例
# ls sample/01_hoge | fn-file-movable

while read -r file_path; do
  digit=$(fn-digit "$(dirname "$file_path")")
  max_number=$((10 ** digit - 1))
  number=$(fn-file-number <<< "$file_path")
  if [ "$number" != "$max_number" ] ; then
    echo "$file_path"
  fi
done
