#!/bin/bash
set -e

# 連番及びファイル・ディレクトリ名から、連番を付与したファイル・ディレクトリ名を取得する。
# 第1引数として、連番を指定する。
# 第2引数として、ファイル・ディレクトリ名を指定する。

# 実行例
# fn-get-path 1 sample/hoge

number="$1"
path="$2"

directory=$(dirname "$path")
digit=$(fn-config-digit "$directory")
number_string=$(printf "%0${digit}d" "$number")
file_name=$(fn-get-name "$path")
echo "${directory}/${number_string}_${file_name}"
