#!/bin/bash
set -e

# 連番及びファイル・ディレクトリ名から、（連番を付与した）ファイル・ディレクトリ名を取得する。
# 第1引数として、ファイル・ディレクトリ名を指定する。
# 第2引数として、連番を指定する。（デフォルトは連番なし）

# 実行例
# fn-get-path sample/hoge
# fn-get-path sample/hoge 1

path="$1"
number="$2"

directory=$(dirname "$path")
if [ -n "$number" ]; then
  digit=$(fn-config-digit "$directory")
  number_string=$(printf "%0${digit}d_" "$number")
fi
file_name=$(basename "$path" | sed "s/^[0-9]*_//")
echo "${directory}/${number_string}${file_name}"
