#!/bin/bash
set -e

# 指定したディレクトリの管理対象の全ファイル・ディレクトリ名に、連番を追加（変更）する。
# 第1引数として、処理対象のディレクトリを指定する。（デフォルトはカレントディレクトリ）

# 実行例
# fn-ls-add
# fn-ls-add sample/01_hoge

# 引数の解析
# 末尾のスラッシュは除去する。
directory="${1:-.}"
directory="${directory%/}"

# 各値の算出
digit=$(fn-config-digit "$directory")
max_number=$((10 ** digit - 1))

# 指定ディレクトリに対しての処理
i=1
fn-ls "$directory" | sort | while read -r file_path; do
  # 連番が最大値以外の場合は変更する。
  number=$(fn-get-number "$file_path")
  if [ "$number" != "$max_number" ] ; then
    fn-add "$file_path" $i
    ((i++))
  fi
done

# サブディレクトリに対しての処理
fn-ls "$directory" | sort | while read -r file_path; do
  if [ -d "$file_path" ]; then
    fn-ls-add "$file_path"
  fi
done
