#!/bin/bash

# File Number Modify
# ファイル名の連番を変更する。
# 第1引数として、連番を指定する。
# 第2引数として、ファイル名を指定する。
# `-d 桁数`オプションで、連番桁数を指定できる。（デフォルトは`2`）

# 実行例
# fn-mod 12 sample/01_hoge
# fn-mod 12 sample/01_hoge/01_aaa

# オプションの解析
digit=2
while getopts f:d: opt; do
  case $opt in
  d) digit="$OPTARG" ;;
  *) exit 1 ;;
  esac
done
shift $((OPTIND - 1))

# 引数の解析
number="$1"
old_path="$2"

# 連番が最大数以外の場合は変更する
new_path=$(fn-path -d "$digit" "$number" "$old_path")
if [ "$(fn-number "$old_path")" -ne $((10 ** digit - 1)) ] && [ "$old_path" != "$new_path" ]; then
  mv "$old_path" "$new_path"
fi
