#!/bin/bash
set -e

# File Number Modify
# ファイル名の連番を変更する。
# 第1引数として、連番を指定する。
# 第2引数として、ファイル名を指定する。

# 実行例
# fn-mod 12 sample/01_hoge
# fn-mod 12 sample/01_hoge/01_aaa

# 引数の解析
new_number="$1"
old_path="$2"

# 各値の算出
directory=$(dirname "$old_path")
digit=$(fn-digit "$directory")
new_number_string=$(printf "%0${digit}d" "$new_number")
file_name=$(fn-name "$old_path")
new_path=${directory}/${new_number_string}_${file_name}

# 連番が最大数以外の場合は変更する
old_number=$(fn-number "$old_path")
max_number=$((10 ** digit - 1))
if [ "$old_number" -ne "$max_number" ] && [ "$old_path" != "$new_path" ]; then
  mv "$old_path" "$new_path"
fi
