#!/bin/bash

# File Number Number
# ファイル名から連番を取得する。
# 引数または標準入力として、ファイル名を指定する。

if [ -n "$1" ]; then
  basename "$1" | grep -oE "^[0-9]+" | sed "s/^0*//"
else
  while read -r file_path; do
    fn-number "$file_path"
  done
fi
