#!/bin/bash
set -e

# File Number Path
# 連番とファイルパスから、ファイルパスを取得する。
# 第1引数として、連番を指定する。
# 第2引数として、ファイル名を指定する。

digit=$(fn-digit "$(dirname "$2")")
echo "$(dirname "$2")/$(printf "%0${digit}d" "$1")_$(fn-name "$2")"
