#!/bin/bash
set -e
PATH="$(dirname "$0"):$PATH"

# 指定したディレクトリの管理対象の全ファイル・ディレクトリ名から、連番を削除する。
# 第1引数として、処理対象のディレクトリを指定する。（デフォルトはカレントディレクトリ）

# 実行例
# fn-rm
# fn-rm sample/01_hoge

# 引数の解析
# 末尾のスラッシュは除去する。
directory="${1:-.}"
directory="${directory%/}"

# 指定ディレクトリに対しての処理
fn-ls "$directory" | sort | while read -r file_path; do
  fn-apply "$file_path"
done

# サブディレクトリに対しての処理
fn-ls "$directory" | sort | while read -r file_path; do
  if [ -d "$file_path" ]; then
    fn-rm "$file_path"
  fi
done
